import { Header, Footer } from "./components";
import dynamic from "next/dynamic";

import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='ru'>
      <body >
        <Header />
             {children}
        <Footer/>
      </body>
    </html>
  );
}
